# This is a basic workflow to help you get started with Actions

name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  # schedule:
  #  - cron: '0 */2 * * *'
  # if: ${{ github.event_name == 'schedule'}}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#env:
#  FLASK_APP: app.py

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: self-hosted
    #needs: build

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # run docker
      - name: Run Docker
        run: |
          make down
          make build
          echo "Deleting old image(s)..."
          docker image prune -a -f

